'use strict';

exports.RPC_OPCODE = {
    HANDSHAKE: 0,
    MESSAGE: 1,
    CLOSE: 2,
    PING: 3,
    PONG: 4
};

exports.RPC_PATH = ((prefix) => {
    if (process.platform !== 'win32') {
        const { XDG_RUNTIME_DIR, TMPDIR, TMP, TEMP } = process.env;
        prefix = (XDG_RUNTIME_DIR || TMPDIR || TMP || TEMP || '/tmp').replace(/\/$/, '') + '/';
    }
    return prefix + 'discord-ipc-';
})('\\\\?\\pipe\\');


exports.RPC_COMMANDS = [
    'DISPATCH',
    'AUTHORIZE',
    'AUTHENTICATE',
    'GET_GUILD',
    'GET_GUILDS',
    'GET_CHANNEL',
    'GET_CHANNELS',
    'CREATE_CHANNEL_INVITE',
    'GET_RELATIONSHIPS',
    'GET_USER',
    'SUBSCRIBE',
    'UNSUBSCRIBE',
    'SET_USER_VOICE_SETTINGS',
    'SET_USER_VOICE_SETTINGS_2',
    'SELECT_VOICE_CHANNEL',
    'GET_SELECTED_VOICE_CHANNEL',
    'SELECT_TEXT_CHANNEL',
    'GET_VOICE_SETTINGS',
    'SET_VOICE_SETTINGS_2',
    'SET_VOICE_SETTINGS',
    'CAPTURE_SHORTCUT',
    'SET_ACTIVITY',
    'SEND_ACTIVITY_JOIN_INVITE',
    'CLOSE_ACTIVITY_JOIN_REQUEST',
    'ACTIVITY_INVITE_USER',
    'ACCEPT_ACTIVITY_INVITE',
    'INVITE_BROWSER',
    'DEEP_LINK',
    'CONNECTIONS_CALLBACK',
    'BRAINTREE_POPUP_BRIDGE_CALLBACK',
    'GIFT_CODE_BROWSER',
    'GUILD_TEMPLATE_BROWSER',
    'OVERLAY',
    'BROWSER_HANDOFF',
    'SET_CERTIFIED_DEVICES',
    'GET_IMAGE',
    'CREATE_LOBBY',
    'UPDATE_LOBBY',
    'DELETE_LOBBY',
    'UPDATE_LOBBY_MEMBER',
    'CONNECT_TO_LOBBY',
    'DISCONNECT_FROM_LOBBY',
    'SEND_TO_LOBBY',
    'SEARCH_LOBBIES',
    'CONNECT_TO_LOBBY_VOICE',
    'DISCONNECT_FROM_LOBBY_VOICE',
    'SET_OVERLAY_LOCKED',
    'OPEN_OVERLAY_ACTIVITY_INVITE',
    'OPEN_OVERLAY_GUILD_INVITE',
    'OPEN_OVERLAY_VOICE_SETTINGS',
    'VALIDATE_APPLICATION',
    'GET_ENTITLEMENT_TICKET',
    'GET_APPLICATION_TICKET',
    'START_PURCHASE',
    'GET_SKUS',
    'GET_ENTITLEMENTS',
    'GET_NETWORKING_CONFIG',
    'NETWORKING_SYSTEM_METRICS',
    'NETWORKING_PEER_METRICS',
    'NETWORKING_CREATE_TOKEN',
    'SET_USER_ACHIEVEMENT',
    'GET_USER_ACHIEVEMENTS'
].reduce((prev, cur) => {
    prev[cur] = cur;
    return prev;
}, {})

exports.RPC_ERRORS = {
    UNKNOWN_ERROR: 1000,
    SERVICE_UNAVAILABLE: 1001,
    TRANSACTION_ABORTED: 1002,
    INVALID_PAYLOAD: 4000,
    INVALID_COMMAND: 4002,
    INVALID_GUILD: 4003,
    INVALID_EVENT: 4004,
    INVALID_CHANNEL: 4005,
    INVALID_PERMISSIONS: 4006,
    INVALID_CLIENTID: 4007,
    INVALID_ORIGIN: 4008,
    INVALID_TOKEN: 4009,
    INVALID_USER: 4010,
    INVALID_INVITE: 4011,
    INVALID_ACTIVITY_JOIN_REQUEST: 4012,
    INVALID_LOBBY: 4013,
    INVALID_ENTITLEMENT: 4015,
    INVALID_LOBBY_SECRET: 4014,
    INVALID_GIFT_CODE: 4016,
    OAUTH2_ERROR: 5000,
    SELECT_CHANNEL_TIMED_OUT: 5001,
    GET_GUILD_TIMED_OUT: 5002,
    SELECT_VOICE_FORCE_REQUIRED: 5003,
    CAPTURE_SHORTCUT_ALREADY_LISTENING: 5004,
    INVALID_ACTIVITY_SECRET: 5005,
    NO_ELIGIBLE_ACTIVITY: 5006,
    LOBBY_FULL: 5007,
    PURCHASE_CANCELED: 5008,
    PURCHASE_ERROR: 5009,
    UNAUTHORIZED_FOR_ACHIEVEMENT: 5010,
    RATE_LIMITED: 5011
};

exports.RPC_CLOSE_CODE = {
    CLOSE_NORMAL: 1000,
    CLOSE_UNSUPPORTED: 1003,
    CLOSE_ABNORMAL: 1006,
    INVALID_CLIENTID: 4000,
    INVALID_ORIGIN: 4001,
    RATELIMITED: 4002,
    TOKEN_REVOKED: 4003,
    INVALID_VERSION: 4004,
    INVALID_ENCODING: 4005
};

exports.LOBBY_TYPE = {
    PRIVATE: 1,
    PUBLIC: 2
};

exports.RELATIONSHIP_TYPE = {
    NONE: 0,
    FRIEND: 1,
    BLOCKED: 2,
    PENDING_INCOMING: 3,
    PENDING_OUTGOING: 4,
    IMPLICIT: 5
};